### ISSUE TITLE
callback defined as required 

### ISSUE THREAD

**Issue by jmls** [samhagman/machinepack-weather#1]
the darksky developer docs (https://developer.forecast.io/docs/v2#options) state that 

"callback=[callback]: Return the API response as JSONP. Please use caution when using this, since exposing your API key to the public is a security hazard " 

so, I removed this option, as I also wanted the api to respond with pure json

However, I now get the error

[Error: For key `callback`: An invalid value was specified:

**Comment by samhagman** [comment]
I just removed `callback` from the options completely since this code is really only designed for server-side use anyways and therefore JSONP response is not very useful.

But as another note I do not believe there is a way to make some of those sub-fields optional.  I.E. If you decide to use the `options` at all you will need to provide all of `units`, `exclude`, `extend`, and `lang`.
